#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jul  4 13:21:34 2020

@author: gabrielochoa
"""
import math

pi = math.pi

radius = int(input("What is the radius of the circle? \n >>>"))

area_of_circle = pi*(radius**2)

print(area_of_circle)

# print(math.pi)