#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jul  4 13:39:54 2020

@author: gabrielochoa
"""


inputFarenheit = int(input("What is the temperature you want to convert into? \n >>>"))

celcius = ((inputFarenheit-32)*(5/9))

print(celcius)