#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jul  4 13:39:54 2020

@author: gabrielochoa
"""


# inputFarenheit = int(input("What is the temperature you want to convert into? \n >>>"))

# celcius = ((inputFarenheit-32)*(5/9))

# print(str(inputFarenheit) +  " Farenheit is equivalent to " + str(celcius) + " Celcius.")

#Better way of writing it in my opinion

far = float(input("Please, enter the temperature in farenheit: \n >>>"))

cel = (far - 32) * (5/9)

print(far, " farenheit is equivalent to ", cel, " celcius")