#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jul  4 14:01:22 2020

@author: gabrielochoa
"""


int_1 = int(input("Please provide the frst number you would like to add. \n >>>"))

int_2 = int(input("Please provide the second number you would like to add. \n >>>"))

sum_of_inputs = int_1 + int_2

print("The sum of both of your inputs is", sum_of_inputs)
