#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jul  4 15:35:09 2020

@author: gabrielochoa
"""

int_1 = int(input("Please enter the first number to be multiplied \n >>>"))

int_2 = int(input("Please enter the second number to be multiplied \n >>>"))

product = int_1 * int_2

print("The product of the two numbers provided is", product)